# Generated by Django 3.2.6 on 2021-08-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hangout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('budget_type', models.CharField(choices=[('least', 'least'), ('median', 'median'), ('average', 'average')], default='least', max_length=7)),
                ('zipcode', models.IntegerField()),
                ('number_submitted', models.IntegerField(default=0)),
            ],
        ),
    ]
