# Generated by Django 3.2.6 on 2021-08-12 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInput', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.IntegerField()),
                ('hangout_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInput.hangout')),
            ],
        ),
    ]
