# Generated by Django 3.2.6 on 2021-08-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInput', '0004_auto_20210812_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgets',
            name='hangout_group',
        ),
        migrations.AddField(
            model_name='budgets',
            name='hangout_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hangout',
            name='group_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hangout',
            name='number_submitted',
            field=models.IntegerField(default=0),
        ),
    ]
