# Generated by Django 3.2.6 on 2021-08-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInput', '0005_auto_20210812_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangout',
            name='budget_type',
            field=models.IntegerField(),
        ),
    ]
