# Generated by Django 3.2.6 on 2021-08-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInput', '0006_alter_hangout_budget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangout',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
