# Generated by Django 3.2.6 on 2021-08-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInput', '0008_alter_hangout_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hangout_id', models.IntegerField()),
                ('final_budget', models.IntegerField()),
            ],
        ),
    ]
