# Generated by Django 3.2.6 on 2021-08-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInput', '0009_finalbudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalbudget',
            name='final_budget',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='finalbudget',
            name='hangout_id',
            field=models.IntegerField(default=-1),
        ),
    ]
