# Generated by Django 3.2.6 on 2021-08-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInput', '0010_auto_20210812_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangout',
            name='group_id',
            field=models.IntegerField(default=10101),
        ),
    ]
