# Generated by Django 3.2.6 on 2021-08-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInput', '0013_alter_hangout_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangout',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
