# Generated by Django 3.2.6 on 2021-08-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recPlaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='ids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='url',
            field=models.CharField(default='o', max_length=300),
            preserve_default=False,
        ),
    ]
