# Generated by Django 3.2.6 on 2021-08-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recPlaces', '0002_auto_20210813_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(default='c', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='url',
            field=models.CharField(default='c', max_length=300),
        ),
    ]
