# Generated by Django 3.2.6 on 2021-08-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recPlaces', '0003_auto_20210813_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
